// data.js — Spark Homes Repair Estimator
// SINGLE SOURCE OF TRUTH for pricing. Generated from the official Pricing_List.csv.
// Do NOT hand-edit prices here; if Spark ships a new CSV, the in-app importer overrides at runtime.
// 108 line items. 19 required groups across 5 sections (Interior/General has 1 extra
// "General & Turnover" group so no item is orphaned). Bedroom & Living reuse interior
// item definitions but live as their own removable room instances (decoupling requirement).

export const ITEMS = {
  "ig-01": { name: "Refinish Hardwood Floor", cost: 2.35, unit: "sqft" },
  "ig-02": { name: "New Hardwoods 1.5\"", cost: 10.0, unit: "sqft" },
  "ig-03": { name: "New Hardwoods 2\"", cost: 4.75, unit: "sqft" },
  "ig-04": { name: "Hardwood Splicing", cost: 8.4, unit: "sqft" },
  "ig-05": { name: "Vinyl Plank", cost: 2.5, unit: "sqft" },
  "ig-06": { name: "Carpet", cost: 1.9, unit: "sqft" },
  "ig-07": { name: "Interior Paint — 2 Tone", cost: 2.95, unit: "sqft" },
  "ig-08": { name: "Drywall Repair", cost: 900.0, unit: "1,000 sqft" },
  "ig-09": { name: "Wallpaper Removal", cost: 250.0, unit: "room" },
  "ig-10": { name: "Interior Door — Hollow Slab", cost: 125.0, unit: "ea." },
  "ig-11": { name: "Interior Door Hardware (Knob + Hinges + Labor)", cost: 25.0, unit: "ea." },
  "ig-12": { name: "Bifold Door with Framing", cost: 400.0, unit: "ea." },
  "ig-13": { name: "Interior Door — Pre-hung", cost: 200.0, unit: "ea." },
  "ig-14": { name: "Front Entry Door", cost: 475.0, unit: "ea." },
  "ig-15": { name: "Front Entry Door Hardware", cost: 80.0, unit: "ea." },
  "ig-16": { name: "Exterior Door Hardware", cost: 75.0, unit: "handle" },
  "ig-17": { name: "Exterior Insulated Side Door (Installed)", cost: 500.0, unit: "ea." },
  "ig-18": { name: "Sliding Glass Door", cost: 1025.0, unit: "ea." },
  "ig-19": { name: "Trim Out (Casing, Crown, Baseboard)", cost: 3.75, unit: "LF" },
  "ig-20": { name: "MISC / Punch List", cost: 2650.0, unit: "flat" },
  "ig-21": { name: "Finish Out Labor", cost: 1350.0, unit: "flat" },
  "ig-22": { name: "Light Fixtures", cost: 70.0, unit: "100 sqft" },
  "ig-23": { name: "Bedbug Spray / Heat Treat", cost: 475.0, unit: "ea." },
  "ig-24": { name: "Termite Treatment", cost: 650.0, unit: "ea." },
  "ig-25": { name: "Demo", cost: 1375.0, unit: "variable" },
  "ig-26": { name: "Haul Off", cost: 725.0, unit: "load" },
  "ig-27": { name: "Final Cleaning", cost: 325.0, unit: "flat" },
  "ig-28": { name: "Staging", cost: 0.9, unit: "sqft" },
  "kt-01": { name: "Hinges and Pulls", cost: 275.0, unit: "kitchen" },
  "kt-02": { name: "Cabinets Uppers", cost: 125.0, unit: "LF" },
  "kt-03": { name: "Cabinets Lowers", cost: 150.0, unit: "LF" },
  "kt-04": { name: "Cabinet Door Faces Only", cost: 80.0, unit: "door" },
  "kt-05": { name: "Cabinets (Labor & Paint)", cost: 1100.0, unit: "kitchen" },
  "kt-06": { name: "Granite + 4\" Splash Guard", cost: 40.0, unit: "LF" },
  "kt-07": { name: "Backsplash", cost: 725.0, unit: "house" },
  "kt-08": { name: "Misc Woodwork", cost: 500.0, unit: "variable" },
  "kt-09": { name: "Tile — Large Areas", cost: 6.45, unit: "sqft" },
  "kt-10": { name: "Tile — Small Areas", cost: 10.0, unit: "sqft" },
  "kt-11": { name: "Undermount Kitchen Sink", cost: 325.0, unit: "ea." },
  "kt-12": { name: "Microwave / Hood", cost: 500.0, unit: "ea." },
  "kt-13": { name: "Range", cost: 725.0, unit: "ea." },
  "kt-14": { name: "Wall Oven", cost: 1075.0, unit: "ea." },
  "kt-15": { name: "Cooktop", cost: 550.0, unit: "ea." },
  "kt-16": { name: "Dishwasher", cost: 575.0, unit: "ea." },
  "kt-17": { name: "Fridge", cost: 1175.0, unit: "ea." },
  "ba-01": { name: "Granite ($/LF)", cost: 35.0, unit: "LF" },
  "ba-02": { name: "New Bottom Vanity", cost: 125.0, unit: "LF" },
  "ba-03": { name: "Home Depot Vanity w/ Sink (18\")", cost: 225.0, unit: "ea." },
  "ba-04": { name: "Toilet", cost: 150.0, unit: "ea." },
  "ba-05": { name: "Tile — Large Areas", cost: 5.8, unit: "sqft" },
  "ba-06": { name: "Tile — Small Areas", cost: 10.0, unit: "sqft" },
  "ba-07": { name: "Reglaze Tub or Chemical Clean", cost: 350.0, unit: "ea." },
  "ba-08": { name: "Reglaze Tub + Surround", cost: 750.0, unit: "ea." },
  "ba-09": { name: "Reglaze Shower", cost: 1325.0, unit: "ea." },
  "ba-10": { name: "Tiled Shower Tear Out + Tile Install", cost: 3100.0, unit: "ea." },
  "ba-11": { name: "Tub Tile Surround Tear Out + Tile Install (incl. tub)", cost: 2250.0, unit: "ea." },
  "ba-12": { name: "Shower Plastic Insert Tear Out + New Insert", cost: 825.0, unit: "ea." },
  "ba-13": { name: "Tub Tear Out + New Insert & Tub", cost: 1575.0, unit: "ea." },
  "ba-14": { name: "Undermount Sink", cost: 150.0, unit: "ea." },
  "ba-15": { name: "Mirror", cost: 200.0, unit: "ea." },
  "ba-16": { name: "HVL (needed if no window)", cost: 275.0, unit: "ea." },
  "as-01": { name: "Furnace", cost: 3350.0, unit: "ea." },
  "as-02": { name: "Condensing Unit", cost: 3300.0, unit: "ea." },
  "as-03": { name: "Package Unit", cost: 4700.0, unit: "ea." },
  "as-04": { name: "A-Coil (if no condensing unit)", cost: 1625.0, unit: "ea." },
  "as-05": { name: "Ducting (if NO HVAC)", cost: 3200.0, unit: "ea." },
  "as-06": { name: "Duct Cleaning — Floor Vents", cost: 550.0, unit: "ea." },
  "as-07": { name: "Window Unit Replacement 220", cost: 575.0, unit: "ea." },
  "as-08": { name: "Hot Water Heater w/ Expansion Tank", cost: 1425.0, unit: "ea." },
  "as-09": { name: "Hot Water Heater Expansion Tank Only", cost: 200.0, unit: "ea." },
  "as-10": { name: "Switches / Outlets", cost: 1400.0, unit: "house" },
  "as-11": { name: "Standard Electrical", cost: 1650.0, unit: "house" },
  "as-12": { name: "Subfloor", cost: 8.2, unit: "sqft" },
  "as-13": { name: "Framing", cost: 950.0, unit: "variable" },
  "as-14": { name: "Structural (Pier)", cost: 375.0, unit: "pier" },
  "as-15": { name: "Structural Foam Injection", cost: 5.85, unit: "sqft of affected area" },
  "as-16": { name: "Roof", cost: 1100.0, unit: "225 sqft L&M" },
  "as-17": { name: "Plumbing", cost: 1000.0, unit: "variable" },
  "as-18": { name: "Electrical Panel Swap to 200A", cost: 2350.0, unit: "ea." },
  "as-19": { name: "Full Electrical Rewire (to Studs)", cost: 5.65, unit: "sqft" },
  "as-20": { name: "Full Electrical Rewire (leaving Drywall)", cost: 9.15, unit: "sqft" },
  "as-21": { name: "Wall Insulation (to Studs)", cost: 1.2, unit: "sqft" },
  "as-22": { name: "Attic Insulation", cost: 1225.0, unit: "1,600 sqft house" },
  "as-23": { name: "New Drywall to Studs (L&M)", cost: 5.2, unit: "sqft" },
  "as-24": { name: "Aluminum Wiring", cost: 2450.0, unit: "variable" },
  "ex-01": { name: "Fence Repair — Chain Link / Wood Gate", cost: 225.0, unit: "variable" },
  "ex-02": { name: "Fence Repair — Chain Link", cost: 275.0, unit: "LF" },
  "ex-03": { name: "Fence Repair — Privacy 6ft", cost: 30.0, unit: "LF" },
  "ex-04": { name: "Landscaping", cost: 450.0, unit: "variable" },
  "ex-05": { name: "Vinyl Siding (10'x10')", cost: 300.0, unit: "square" },
  "ex-06": { name: "Tuck Pointing", cost: 225.0, unit: "variable" },
  "ex-07": { name: "Exterior Paint", cost: 2.6, unit: "sqft" },
  "ex-08": { name: "Exterior Wood Repair", cost: 525.0, unit: "variable" },
  "ex-09": { name: "Siding Repair (10'x10')", cost: 975.0, unit: "section" },
  "ex-10": { name: "Tree Trimming", cost: 450.0, unit: "variable" },
  "ex-11": { name: "Tree Removal (w/o stump)", cost: 1450.0, unit: "tree" },
  "ex-12": { name: "Stump Grinding", cost: 250.0, unit: "stump" },
  "ex-13": { name: "Aluminum Window Paint (Int/Ext)", cost: 700.0, unit: "house" },
  "ex-14": { name: "Windows (3x5 sash)", cost: 425.0, unit: "ea." },
  "ex-15": { name: "Window Repair — Non-Insulated (6x6+)", cost: 35.0, unit: "sf" },
  "ex-16": { name: "Window Repair — Insulated (6x6+)", cost: 40.0, unit: "sf" },
  "ex-17": { name: "Aluminum Framed Window Pane", cost: 100.0, unit: "pane" },
  "ex-18": { name: "Guttering", cost: 4.15, unit: "LF" },
  "ex-19": { name: "Concrete w/ Demo", cost: 200.0, unit: "sqft" },
  "ex-20": { name: "Mowing (summer, every 2 weeks)", cost: 45.0, unit: "mowing" },
  "ex-21": { name: "Garage Door — 1 Car", cost: 975.0, unit: "ea." },
  "ex-22": { name: "Garage Door — 2 Car (Installed)", cost: 1225.0, unit: "ea." },
  "ex-23": { name: "Garage Conversion", cost: 8850.0, unit: "ea." },
};

export const ROOM_TYPES = [
  { type: "house", label: "Interior / General", singleton: true, groups: [
    { key: "flooring", label: "Flooring", items: ["ig-01", "ig-02", "ig-03", "ig-04", "ig-05", "ig-06"] },
    { key: "paint", label: "Paint & Wall Repair", items: ["ig-07", "ig-08", "ig-09"] },
    { key: "doors", label: "Doors", items: ["ig-10", "ig-11", "ig-12", "ig-13", "ig-14", "ig-15", "ig-16", "ig-17", "ig-18", "ig-19"] },
    { key: "pest", label: "Pest Control", items: ["ig-23", "ig-24"] },
    { key: "general", label: "General & Turnover", items: ["ig-20", "ig-21", "ig-22", "ig-25", "ig-26", "ig-27", "ig-28"] },
  ]},
  { type: "kitchen", label: "Kitchen", singleton: false, groups: [
    { key: "cabinets", label: "Cabinets", items: ["kt-01", "kt-02", "kt-03", "kt-04", "kt-05"] },
    { key: "counters", label: "Countertops & Tile", items: ["kt-06", "kt-07", "kt-08", "kt-09", "kt-10"] },
    { key: "appliances", label: "Appliances", items: ["kt-11", "kt-12", "kt-13", "kt-14", "kt-15", "kt-16", "kt-17"] },
  ]},
  { type: "bathroom", label: "Bathroom", singleton: false, groups: [
    { key: "vanity", label: "Vanity & Countertop", items: ["ba-01", "ba-02", "ba-03", "ba-14", "ba-15", "ba-16"] },
    { key: "tub", label: "Tub & Shower", items: ["ba-04", "ba-07", "ba-08", "ba-09", "ba-10", "ba-11", "ba-12", "ba-13"] },
    { key: "tile", label: "Tile", items: ["ba-05", "ba-06"] },
  ]},
  { type: "systems", label: "Systems & Structure", singleton: true, groups: [
    { key: "hvac", label: "HVAC", items: ["as-01", "as-02", "as-03", "as-04", "as-05", "as-06", "as-07", "as-08", "as-09"] },
    { key: "electrical", label: "Electrical", items: ["as-10", "as-11", "as-18", "as-19", "as-20", "as-24"] },
    { key: "structural", label: "Structural", items: ["as-12", "as-13", "as-14", "as-15", "as-16", "as-17"] },
    { key: "insulation", label: "Insulation & Drywall", items: ["as-21", "as-22", "as-23"] },
  ]},
  { type: "exterior", label: "Exterior", singleton: true, groups: [
    { key: "fence", label: "Fence", items: ["ex-01", "ex-02", "ex-03"] },
    { key: "siding", label: "Siding", items: ["ex-05", "ex-06", "ex-07", "ex-08", "ex-09", "ex-18"] },
    { key: "windows", label: "Windows", items: ["ex-13", "ex-14", "ex-15", "ex-16", "ex-17"] },
    { key: "garage", label: "Garage", items: ["ex-21", "ex-22", "ex-23"] },
    { key: "trees", label: "Trees & Landscaping", items: ["ex-04", "ex-10", "ex-11", "ex-12", "ex-19", "ex-20"] },
  ]},
  { type: "bedroom", label: "Bedroom", singleton: false, groups: [
    { key: "flooring", label: "Flooring", items: ["ig-01", "ig-02", "ig-03", "ig-04", "ig-05", "ig-06"] },
    { key: "paint", label: "Paint", items: ["ig-07", "ig-08", "ig-09"] },
    { key: "doors", label: "Doors", items: ["ig-10", "ig-11", "ig-13"] },
    { key: "closet", label: "Closet", items: ["ig-12", "ig-19"] },
  ]},
  { type: "living", label: "Living / Common", singleton: false, groups: [
    { key: "flooring", label: "Flooring", items: ["ig-01", "ig-02", "ig-03", "ig-04", "ig-05", "ig-06"] },
    { key: "paint", label: "Paint", items: ["ig-07", "ig-08", "ig-09"] },
    { key: "doors", label: "Doors", items: ["ig-10", "ig-11", "ig-13"] },
    { key: "lighting", label: "Lighting", items: ["ig-22"] },
  ]},
];
